FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html
COPY auth.html /usr/share/nginx/html/auth.html
COPY app.js /usr/share/nginx/html/app.js
COPY styles.css /usr/share/nginx/html/styles.css
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
